# Generated by Django 5.2.12 on 2026-03-05 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('TI', 'TI / Informática'), ('INFRA', 'Infraestrutura'), ('SEGURANCA', 'Segurança'), ('VISITANTE', 'Visitantes / Portaria'), ('MANUTENCAO', 'Manutenção')], max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO', 'Aguardando'), ('RESOLVIDO', 'Resolvido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('departamento_destino', models.CharField(blank=True, help_text='Departamento/setor que deve atender o chamado.', max_length=100)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chamados/anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
