# Generated by Django 5.1.8 on 2025-11-16 23:02

import django.utils.timezone
import tenant_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_support', models.BooleanField(default=False, help_text='Mensagem enviada pela equipe?')),
                ('texto', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=tenant_management.models.caminho_screenshot_chat)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_id', models.IntegerField(blank=True, null=True)),
                ('obra_nome', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversa de Suporte',
                'verbose_name_plural': 'Conversas de Suporte',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do cliente/empresa', max_length=100, unique=True)),
                ('schema_name', models.CharField(help_text='Nome do schema no PostgreSQL', max_length=63, unique=True)),
                ('paid_until', models.DateField(default=django.utils.timezone.now, help_text='Data até a qual o plano está ativo')),
                ('on_trial', models.BooleanField(default=True, help_text='Está em período de teste?')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ (somente números)', max_length=18, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato do tenant (deixe em branco ao criar, preencha depois)', max_length=254, null=True, unique=True)),
                ('espaco_extra_mb', models.PositiveIntegerField(default=0, help_text='MB adicionais ao limite padrão')),
                ('plano', models.CharField(choices=[('trial', 'Trial (7 dias)'), ('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='trial', help_text='Plano contratado', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do tenant')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domínio (ex: cliente.minhaobra.com)', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True, help_text='É o domínio principal deste tenant?')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
            },
        ),
        migrations.CreateModel(
            name='EmailDepoimentoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(max_length=254)),
                ('nome_destinatario', models.CharField(max_length=200)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email de Depoimento Enviado',
                'verbose_name_plural': 'Emails de Depoimento Enviados',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='EspacoExtraRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail do cliente que fez a solicitação', max_length=254)),
                ('schema', models.CharField(help_text='Schema do tenant que solicitou', max_length=100)),
                ('quantidade_gb', models.PositiveIntegerField(help_text='Quantidade de GB solicitados')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Espaço Extra',
                'verbose_name_plural': 'Solicitações de Espaço Extra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_programada', models.DateField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Informativo',
                'verbose_name_plural': 'Informativos',
                'ordering': ['-data_programada'],
            },
        ),
        migrations.CreateModel(
            name='LeituraInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LojaDistribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da loja')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Responsável / contato')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativa', models.BooleanField(default=True, verbose_name='Loja ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrada em')),
            ],
            options={
                'verbose_name': 'Loja distribuidora',
                'verbose_name_plural': 'Lojas distribuidoras',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='OrigemCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome interno da campanha')),
                ('plataforma', models.CharField(choices=[('google', 'Google Ads'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('email', 'E-mail Marketing'), ('loja', 'Loja física com QR Code'), ('outra', 'Outra')], max_length=50, verbose_name='Plataforma')),
                ('utm_source', models.CharField(help_text='Ex: google, instagram, loja', max_length=100, verbose_name='utm_source')),
                ('utm_medium', models.CharField(help_text='Ex: cpc, social, qrcode, promo', max_length=100, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, help_text='Ex: blackfriday, loja1', max_length=100, verbose_name='utm_campaign')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição ou observações')),
                ('link_destino', models.URLField(default='https://appname.grfgraph.com.br/login/assinar-trial/', verbose_name='URL base de destino')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início da campanha')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da campanha')),
                ('ativa', models.BooleanField(default=True, verbose_name='Campanha ativa?')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Campanha / origem de acesso',
                'verbose_name_plural': 'Campanhas / origens de acesso',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PaginaVisitaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('assinar', 'Assinar'), ('renovar', 'Renovar'), ('trial', 'Trial')], max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('visitado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Campaign')),
                ('loja_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Loja (utm)')),
            ],
            options={
                'verbose_name': 'Log de Visita',
                'verbose_name_plural': 'Logs de Visitas',
                'ordering': ['-visitado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('assinatura', 'Assinatura'), ('renovacao', 'Renovação')], default='assinatura', help_text='Tipo de solicitação: assinatura nova ou renovação.', max_length=12)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('documento', models.CharField(help_text='CPF ou CNPJ', max_length=25)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('plano', models.CharField(choices=[('trial', 'Teste gratuito (7 dias)'), ('mensal', 'Mensal – R$ 55,99'), ('semestral', 'Semestral – R$ 209,99'), ('anual', 'Anual – R$ 388,99')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
            ],
            options={
                'verbose_name': 'Pedido de Assinatura',
                'verbose_name_plural': 'Pedidos de Assinatura',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TenantDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
            ],
            options={
                'verbose_name': 'Solicitação de Exclusão',
                'verbose_name_plural': 'Solicitações de Exclusão',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_criado', models.EmailField(blank=True, max_length=254, null=True)),
                ('schema_criado', models.CharField(blank=True, max_length=100, null=True)),
                ('dados_recebidos', models.JSONField()),
                ('resposta_enviada', models.TextField(blank=True, null=True)),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhooks',
                'ordering': ['-recebido_em'],
            },
        ),
    ]
