# Generated by Django 5.1.8 on 2025-11-16 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='tenant_management.chatthread'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_management.client'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant_management.client'),
        ),
        migrations.AddField(
            model_name='emaildepoimentoenviado',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_depoimento', to='tenant_management.client'),
        ),
        migrations.AddField(
            model_name='emaildepoimentoenviado',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espacoextrarequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espacos', to='tenant_management.client'),
        ),
        migrations.AddField(
            model_name='leiturainformativo',
            name='informativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_management.informativo'),
        ),
        migrations.AddField(
            model_name='leiturainformativo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='origemcampanha',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Se a campanha está associada a uma loja física', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_management.lojadistribuidora'),
        ),
        migrations.AddField(
            model_name='tenantdeleterequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantdeleterequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantdeleterequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to='tenant_management.client'),
        ),
        migrations.AlterUniqueTogether(
            name='emaildepoimentoenviado',
            unique_together={('client', 'email_destinatario')},
        ),
        migrations.AlterUniqueTogether(
            name='leiturainformativo',
            unique_together={('informativo', 'usuario')},
        ),
    ]
