# Generated by Django 5.1.8 on 2025-12-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plano',
            field=models.CharField(choices=[('trial', 'Trial (5 dias)'), ('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='trial', help_text='Plano contratado', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='plano',
            field=models.CharField(choices=[('trial', 'Teste gratuito (5 dias)'), ('mensal', 'Mensal – R$ 55,99'), ('semestral', 'Semestral – R$ 209,99'), ('anual', 'Anual – R$ 388,99')], max_length=20),
        ),
    ]
