# Generated by Django 5.2.12 on 2026-03-05 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PORTARIA', 'Portaria'), ('GERENTE_ADMIN', 'Gerente administrativo'), ('TI', 'TI / Informática'), ('COMPRAS', 'Compras'), ('INFRA', 'Infraestrutura'), ('SEGURANCA', 'Segurança'), ('OUTRO', 'Outro')], default='OUTRO', max_length=32)),
                ('display_name', models.CharField(blank=True, help_text='Nome exibido na lista de conversas (opcional).', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
