# Generated by Django 5.2.12 on 2026-03-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Departamento/setor do colaborador (ex.: Portaria, TI, Compras).', max_length=100),
        ),
    ]
