# Generated by Django 5.2.12 on 2026-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, help_text='Empresa (ex.: Kuttner do Brasil, Kuttner Automation).', max_length=100),
        ),
    ]
