# Generated by Django 5.2.12 on 2026-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto do perfil exibida no chat.', null=True, upload_to='avatars/'),
        ),
    ]
